FROM alpine:3.5
RUN echo "Hello Docker"

LABEL name="learning-docker"
LABEL email="[email protected]"
LABEL "com.example.vendor"="ACME Incorporated"
LABEL com.example.label-with-value="foo"
LABEL version="1.0"
LABEL description="This text illustrates\ 
that label-values can span multiple lines."
